baseURL = "https://www.dixitmudit.in/"
title = "Computational Catalysis and Electrochemistry Lab (CompCEL)"
[params]
  author = "Mudit Dixit"
  sitename = "Mudit Dixit's Page"
  twitter = "@dixitmuditk"
